version: "3"
services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=api_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=api_db
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - db_data:/var/lib/mysql
      - ./setup/api.sql:/docker-entrypoint-initdb.d/1-dump.sql
  flask_app:
    build:
      context: .
      dockerfile: application.Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql
