#!/usr/bin/env python3
# import requests
# session = 'f5828c84-71bf-41be-8bc8-510d4534ccc6'
# key = 'b960f4e5-bb29-4c27-9e4f-c4b4424996db'
# headers = {'X-APIEMPIR-KEY': key, 'session-id': session}
# body = {'price': 100, 'currency': 'USD'}
# url = 'http://127.0.0.1:5000/api/v1/payment/create'

# data = requests.post(url, data=body, headers=headers)
# print(data.json())
response_ex = '''{
    "body": {
        "location": {
            "name": "Alexandria",
            "region": "Al Iskandariyah",
            "country": "Egypt",
            "lat": 31.2,
            "lon": 29.92,
            "tz_id": "Africa/Cairo",
            "localtime_epoch": 1710506411,
            "localtime": "2024-03-15 14:40"
        },
        "current": {
            "last_updated_epoch": 1710505800,
            "last_updated": "2024-03-15 14:30",
            "temp_c": 20.0,
            "temp_f": 68.0,
            "is_day": 1,
            "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 300,
            "wind_dir": "WNW",
            "pressure_mb": 1018.0,
            "pressure_in": 30.06,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 53,
            "cloud": 50,
            "feelslike_c": 20.0,
            "feelslike_f": 68.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "uv": 5.0,
            "gust_mph": 12.3,
            "gust_kph": 19.9
        },
        "forecast": {
            "forecastday": [
                {
                    "date": "2024-03-15",
                    "date_epoch": 1710460800,
                    "day": {
                        "maxtemp_c": 18.8,
                        "maxtemp_f": 65.8,
                        "mintemp_c": 15.2,
                        "mintemp_f": 59.3,
                        "avgtemp_c": 16.8,
                        "avgtemp_f": 62.2,
                        "maxwind_mph": 11.2,
                        "maxwind_kph": 18.0,
                        "totalprecip_mm": 0.0,
                        "totalprecip_in": 0.0,
                        "totalsnow_cm": 0.0,
                        "avgvis_km": 10.0,
                        "avgvis_miles": 6.0,
                        "avghumidity": 62,
                        "daily_will_it_rain": 0,
                        "daily_chance_of_rain": 0,
                        "daily_will_it_snow": 0,
                        "daily_chance_of_snow": 0,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "uv": 6.0
                    },
                    "astro": {
                        "sunrise": "06:10 AM",
                        "sunset": "06:09 PM",
                        "moonrise": "09:22 AM",
                        "moonset": "No moonset",
                        "moon_phase": "Waxing Crescent",
                        "moon_illumination": 28,
                        "is_moon_up": 0,
                        "is_sun_up": 0
                    },
                    "hour": [
                        {
                            "time_epoch": 1710511200,
                            "time": "2024-03-15 16:00",
                            "temp_c": 18.3,
                            "temp_f": 64.9,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 10.5,
                            "wind_kph": 16.9,
                            "wind_degree": 318,
                            "wind_dir": "NW",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.05,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 55,
                            "cloud": 2,
                            "feelslike_c": 18.3,
                            "feelslike_f": 64.9,
                            "windchill_c": 18.3,
                            "windchill_f": 64.9,
                            "heatindex_c": 18.3,
                            "heatindex_f": 64.9,
                            "dewpoint_c": 9.3,
                            "dewpoint_f": 48.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.2,
                            "gust_kph": 21.2,
                            "uv": 5.0,
                            "short_rad": 655.8,
                            "diff_rad": 98.4
                        },
                        {
                            "time_epoch": 1710514800,
                            "time": "2024-03-15 17:00",
                            "temp_c": 17.9,
                            "temp_f": 64.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 9.6,
                            "wind_kph": 15.5,
                            "wind_degree": 328,
                            "wind_dir": "NNW",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.05,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 57,
                            "cloud": 0,
                            "feelslike_c": 17.9,
                            "feelslike_f": 64.1,
                            "windchill_c": 17.9,
                            "windchill_f": 64.1,
                            "heatindex_c": 17.9,
                            "heatindex_f": 64.1,
                            "dewpoint_c": 9.2,
                            "dewpoint_f": 48.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 12.3,
                            "gust_kph": 19.8,
                            "uv": 5.0,
                            "short_rad": 501.92,
                            "diff_rad": 88.58
                        },
                        {
                            "time_epoch": 1710518400,
                            "time": "2024-03-15 18:00",
                            "temp_c": 17.0,
                            "temp_f": 62.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 8.3,
                            "wind_kph": 13.3,
                            "wind_degree": 325,
                            "wind_dir": "NW",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.06,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 59,
                            "cloud": 0,
                            "feelslike_c": 17.0,
                            "feelslike_f": 62.7,
                            "windchill_c": 17.0,
                            "windchill_f": 62.7,
                            "heatindex_c": 17.0,
                            "heatindex_f": 62.7,
                            "dewpoint_c": 9.0,
                            "dewpoint_f": 48.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.8,
                            "gust_kph": 19.0,
                            "uv": 5.0,
                            "short_rad": 396.58,
                            "diff_rad": 74.13
                        },
                        {
                            "time_epoch": 1710522000,
                            "time": "2024-03-15 19:00",
                            "temp_c": 16.6,
                            "temp_f": 61.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 7.8,
                            "wind_kph": 12.6,
                            "wind_degree": 332,
                            "wind_dir": "NNW",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.07,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 61,
                            "cloud": 0,
                            "feelslike_c": 16.6,
                            "feelslike_f": 61.9,
                            "windchill_c": 16.6,
                            "windchill_f": 61.9,
                            "heatindex_c": 16.6,
                            "heatindex_f": 61.9,
                            "dewpoint_c": 9.0,
                            "dewpoint_f": 48.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.7,
                            "gust_kph": 18.8,
                            "uv": 1.0,
                            "short_rad": 317.31,
                            "diff_rad": 59.33
                        },
                        {
                            "time_epoch": 1710525600,
                            "time": "2024-03-15 20:00",
                            "temp_c": 16.4,
                            "temp_f": 61.5,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.9,
                            "wind_kph": 11.2,
                            "wind_degree": 344,
                            "wind_dir": "NNW",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.08,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 61,
                            "cloud": 0,
                            "feelslike_c": 16.4,
                            "feelslike_f": 61.5,
                            "windchill_c": 16.4,
                            "windchill_f": 61.5,
                            "heatindex_c": 16.4,
                            "heatindex_f": 61.5,
                            "dewpoint_c": 8.9,
                            "dewpoint_f": 48.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 10.5,
                            "gust_kph": 16.8,
                            "uv": 1.0,
                            "short_rad": 264.43,
                            "diff_rad": 49.44
                        },
                        {
                            "time_epoch": 1710529200,
                            "time": "2024-03-15 21:00",
                            "temp_c": 16.2,
                            "temp_f": 61.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 5.8,
                            "wind_kph": 9.4,
                            "wind_degree": 335,
                            "wind_dir": "NNW",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.1,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 62,
                            "cloud": 0,
                            "feelslike_c": 16.2,
                            "feelslike_f": 61.1,
                            "windchill_c": 16.2,
                            "windchill_f": 61.1,
                            "heatindex_c": 16.2,
                            "heatindex_f": 61.1,
                            "dewpoint_c": 8.8,
                            "dewpoint_f": 47.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.0,
                            "gust_kph": 14.5,
                            "uv": 1.0,
                            "short_rad": 0.0,
                            "diff_rad": 0.0
                        },
                        {
                            "time_epoch": 1710532800,
                            "time": "2024-03-15 22:00",
                            "temp_c": 16.0,
                            "temp_f": 60.8,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.0,
                            "wind_kph": 9.7,
                            "wind_degree": 341,
                            "wind_dir": "NNW",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.1,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 63,
                            "cloud": 0,
                            "feelslike_c": 16.0,
                            "feelslike_f": 60.8,
                            "windchill_c": 16.0,
                            "windchill_f": 60.8,
                            "heatindex_c": 16.0,
                            "heatindex_f": 60.8,
                            "dewpoint_c": 8.9,
                            "dewpoint_f": 48.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.5,
                            "gust_kph": 15.2,
                            "uv": 1.0,
                            "short_rad": 0.0,
                            "diff_rad": 0.0
                        },
                        {
                            "time_epoch": 1710536400,
                            "time": "2024-03-15 23:00",
                            "temp_c": 15.8,
                            "temp_f": 60.5,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly Cloudy ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 7.8,
                            "wind_kph": 12.6,
                            "wind_degree": 353,
                            "wind_dir": "N",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.09,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 64,
                            "cloud": 25,
                            "feelslike_c": 15.8,
                            "feelslike_f": 60.5,
                            "windchill_c": 15.8,
                            "windchill_f": 60.5,
                            "heatindex_c": 15.8,
                            "heatindex_f": 60.5,
                            "dewpoint_c": 9.1,
                            "dewpoint_f": 48.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 12.3,
                            "gust_kph": 19.8,
                            "uv": 1.0,
                            "short_rad": 0.0,
                            "diff_rad": 0.0
                        }
                    ]
                }
            ]
        }
    }
}'''


print(eval(response_ex))
