#!/usr/bin/env python3
# endpoint_title, endpoint_url, method, description, response_ex, category, api_id
import mysql.connector
from PIL import Image
import base64


THEURL = 'https://apiempire.site/api'


# Establish connection to MySQL
connection = mysql.connector.connect(
    host="localhost",
    user="api_user",
    password="password",
    database="api_db"
)

cursor = connection.cursor()

# Define data
title = "Weather API"
description = "WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy."
category = "weather"
image_cover = Image.open("image.jpg")
with open("image.jpg", "rb") as image_file:
    image = f'data:image/{image_cover.format};base64,{base64.b64encode(image_file.read()).decode()}'
# Insert data into the table
insert_query = "INSERT INTO API (title, description, category, image_cover) VALUES (%s, %s, %s, %s)"
cursor.execute(insert_query, (title, description, category, image))
endpoint_title = 'current'
endpoint_url = f'{THEURL}/weather/current?city=city&aqi=(yes,no)'
method = 'GET'
description = 'Get the current weather for a city.\
    takes from query parameter city like ?q=city\
        takes aqi parameter to get air quality index like ?q=city&aqi=yes'
response_ex = """{
body:{
    "location": {
        "name": "Alexandria",
        "region": "Al Iskandariyah",
        "country": "Egypt",
        "lat": 31.2,
        "lon": 29.92,
        "tz_id": "Africa/Cairo",
        "localtime_epoch": 1710456336,
        "localtime": "2024-03-15 0:45"
    },
    "current": {
        "last_updated_epoch": 1710456300,
        "last_updated": "2024-03-15 00:45",
        "temp_c": 13.0,
        "temp_f": 55.4,
        "is_day": 0,
        "condition": {
            "text": "Clear",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 3.8,
        "wind_kph": 6.1,
        "wind_degree": 150,
        "wind_dir": "SSE",
        "pressure_mb": 1017.0,
        "pressure_in": 30.03,
        "precip_mm": 0.0,
        "precip_in": 0.0,
        "humidity": 77,
        "cloud": 0,
        "feelslike_c": 12.2,
        "feelslike_f": 53.9,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 1.0,
        "gust_mph": 10.4,
        "gust_kph": 16.8
    }
}
"""
category = "weather"
cursor.execute("SELECT id FROM API WHERE title = 'Weather API'")
api_id = cursor.fetchone()[0]
_ = cursor.fetchall()
cursor.execute(
    "INSERT INTO endpoint (title, url, method, description, response_ex, category, api_id) VALUES (%s, %s, %s, %s, %s, %s, %s)",
    (endpoint_title,
     endpoint_url,
     method,
     description,
     response_ex,
     category,
     api_id))
endpoint_title = 'forecast'
endpoint_url = f'{THEURL}/weather/forecast?q=city&days=int&aqi=(yes,no)&alerts=(yes,no)'
method = 'GET'
description = 'Get the 5 day weather forecast for a city.\
    takes from query parameter city like ?q=city\
        takes aqi parameter to get air quality index like ?q=city&aqi=yes\
            takes days parameter to get the forecast for the next 1 to 10 days like ?q=city&days=5\
                takes hour parameter to get the forecast for every hour like ?q=city&hour=24\
                    takes language parameter to get the forecast in the language like ?q=city&lang=ar\
                        takes the date parameter to get the forecast for a specific date like ?q=city&dt=2024-03-15\
                            takes the timezone parameter to get the forecast in the timezone like ?q=city&tz=Europe/London\
                                takes the alerts parameter to get the weather alerts like ?q=city&alerts=yes'
response_ex = '''{
body:{
    "location": {
        "name": "Alexandria",
        "region": "Al Iskandariyah",
        "country": "Egypt",
        "lat": 31.2,
        "lon": 29.92,
        "tz_id": "Africa/Cairo",
        "localtime_epoch": 1710506411,
        "localtime": "2024-03-15 14:40"
    },
    "current": {
        "last_updated_epoch": 1710505800,
        "last_updated": "2024-03-15 14:30",
        "temp_c": 20.0,
        "temp_f": 68.0,
        "is_day": 1,
        "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
        },
        "wind_mph": 9.4,
        "wind_kph": 15.1,
        "wind_degree": 300,
        "wind_dir": "WNW",
        "pressure_mb": 1018.0,
        "pressure_in": 30.06,
        "precip_mm": 0.0,
        "precip_in": 0.0,
        "humidity": 53,
        "cloud": 50,
        "feelslike_c": 20.0,
        "feelslike_f": 68.0,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 5.0,
        "gust_mph": 12.3,
        "gust_kph": 19.9
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2024-03-15",
                "date_epoch": 1710460800,
                "day": {
                    "maxtemp_c": 18.8,
                    "maxtemp_f": 65.8,
                    "mintemp_c": 15.2,
                    "mintemp_f": 59.3,
                    "avgtemp_c": 16.8,
                    "avgtemp_f": 62.2,
                    "maxwind_mph": 11.2,
                    "maxwind_kph": 18.0,
                    "totalprecip_mm": 0.0,
                    "totalprecip_in": 0.0,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 10.0,
                    "avgvis_miles": 6.0,
                    "avghumidity": 62,
                    "daily_will_it_rain": 0,
                    "daily_chance_of_rain": 0,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "uv": 6.0
                },
                "astro": {
                    "sunrise": "06:10 AM",
                    "sunset": "06:09 PM",
                    "moonrise": "09:22 AM",
                    "moonset": "No moonset",
                    "moon_phase": "Waxing Crescent",
                    "moon_illumination": 28,
                    "is_moon_up": 0,
                    "is_sun_up": 0
                },
                "hour": [
                    {
                        "time_epoch": 1710453600,
                        "time": "2024-03-15 00:00",
                        "temp_c": 15.7,
                        "temp_f": 60.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.9,
                        "wind_kph": 7.9,
                        "wind_degree": 315,
                        "wind_dir": "NW",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.05,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 67,
                        "cloud": 8,
                        "feelslike_c": 15.7,
                        "feelslike_f": 60.3,
                        "windchill_c": 15.7,
                        "windchill_f": 60.3,
                        "heatindex_c": 15.7,
                        "heatindex_f": 60.3,
                        "dewpoint_c": 9.7,
                        "dewpoint_f": 49.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.9,
                        "gust_kph": 12.7,
                        "uv": 1.0,
                        "short_rad": 0.0,
                        "diff_rad": 0.0
                    },
                    {
                        "time_epoch": 1710457200,
                        "time": "2024-03-15 01:00",
                        "temp_c": 15.7,
                        "temp_f": 60.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.0,
                        "wind_kph": 9.7,
                        "wind_degree": 303,
                        "wind_dir": "WNW",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.05,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 68,
                        "cloud": 11,
                        "feelslike_c": 15.7,
                        "feelslike_f": 60.2,
                        "windchill_c": 15.7,
                        "windchill_f": 60.2,
                        "heatindex_c": 15.7,
                        "heatindex_f": 60.2,
                        "dewpoint_c": 9.8,
                        "dewpoint_f": 49.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.7,
                        "gust_kph": 15.7,
                        "uv": 1.0,
                        "short_rad": 0.0,
                        "diff_rad": 0.0
                    },
                    {
                        "time_epoch": 1710460800,
                        "time": "2024-03-15 02:00",
                        "temp_c": 15.6,
                        "temp_f": 60.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.0,
                        "wind_kph": 9.7,
                        "wind_degree": 293,
                        "wind_dir": "WNW",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.04,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 69,
                        "cloud": 9,
                        "feelslike_c": 15.6,
                        "feelslike_f": 60.1,
                        "windchill_c": 15.6,
                        "windchill_f": 60.1,
                        "heatindex_c": 15.6,
                        "heatindex_f": 60.1,
                        "dewpoint_c": 10.0,
                        "dewpoint_f": 50.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.8,
                        "gust_kph": 15.7,
                        "uv": 1.0,
                        "short_rad": 0.0,
                        "diff_rad": 0.0
                    },
                    {
                        "time_epoch": 1710464400,
                        "time": "2024-03-15 03:00",
                        "temp_c": 15.5,
                        "temp_f": 60.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.5,
                        "wind_kph": 10.4,
                        "wind_degree": 280,
                        "wind_dir": "W",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.03,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 70,
                        "cloud": 9,
                        "feelslike_c": 15.6,
                        "feelslike_f": 60.0,
                        "windchill_c": 15.6,
                        "windchill_f": 60.0,
                        "heatindex_c": 15.6,
                        "heatindex_f": 60.0,
                        "dewpoint_c": 10.2,
                        "dewpoint_f": 50.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.6,
                        "gust_kph": 17.1,
                        "uv": 1.0,
                        "short_rad": 0.0,
                        "diff_rad": 0.0
                    },
                    {
                        "time_epoch": 1710468000,
                        "time": "2024-03-15 04:00",
                        "temp_c": 15.5,
                        "temp_f": 59.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.7,
                        "wind_kph": 10.8,
                        "wind_degree": 286,
                        "wind_dir": "WNW",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.02,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 71,
                        "cloud": 10,
                        "feelslike_c": 15.5,
                        "feelslike_f": 59.8,
                        "windchill_c": 15.5,
                        "windchill_f": 59.8,
                        "heatindex_c": 15.5,
                        "heatindex_f": 59.8,
                        "dewpoint_c": 10.3,
                        "dewpoint_f": 50.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.0,
                        "gust_kph": 17.7,
                        "uv": 1.0,
                        "short_rad": 0.0,
                        "diff_rad": 0.0
                    },
                    {
                        "time_epoch": 1710471600,
                        "time": "2024-03-15 05:00",
                        "temp_c": 15.4,
                        "temp_f": 59.6,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 6.3,
                        "wind_kph": 10.1,
                        "wind_degree": 282,
                        "wind_dir": "WNW",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.03,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 72,
                        "cloud": 27,
                        "feelslike_c": 15.4,
                        "feelslike_f": 59.6,
                        "windchill_c": 15.4,
                        "windchill_f": 59.6,
                        "heatindex_c": 15.4,
                        "heatindex_f": 59.6,
                        "dewpoint_c": 10.3,
                        "dewpoint_f": 50.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.4,
                        "gust_kph": 16.7,
                        "uv": 1.0,
                        "short_rad": 0.0,
                        "diff_rad": 0.0
                    },
                    {
                        "time_epoch": 1710475200,
                        "time": "2024-03-15 06:00",
                        "temp_c": 15.2,
                        "temp_f": 59.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 5.6,
                        "wind_kph": 9.0,
                        "wind_degree": 279,
                        "wind_dir": "W",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.04,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 73,
                        "cloud": 44,
                        "feelslike_c": 15.2,
                        "feelslike_f": 59.3,
                        "windchill_c": 15.2,
                        "windchill_f": 59.3,
                        "heatindex_c": 15.2,
                        "heatindex_f": 59.3,
                        "dewpoint_c": 10.3,
                        "dewpoint_f": 50.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.4,
                        "gust_kph": 15.0,
                        "uv": 1.0,
                        "short_rad": 0.0,
                        "diff_rad": 0.0
                    },
                    {
                        "time_epoch": 1710478800,
                        "time": "2024-03-15 07:00",
                        "temp_c": 15.6,
                        "temp_f": 60.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 5.6,
                        "wind_kph": 9.0,
                        "wind_degree": 280,
                        "wind_dir": "W",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.05,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 71,
                        "cloud": 52,
                        "feelslike_c": 15.6,
                        "feelslike_f": 60.0,
                        "windchill_c": 15.6,
                        "windchill_f": 60.0,
                                "short_rad": 614.92,
                                "diff_rad": 109.54
                            }
                        ]
                        "short_rad": 677.12,
                        "diff_rad": 111.78
                    },
                    {
                        "time_epoch": 1710500400,
                        "time": "2024-03-15 13:00",
                        "temp_c": 18.9,
                        "temp_f": 66.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 10.1,
                        "wind_kph": 16.2,
                        "wind_degree": 304,
                        "wind_dir": "NW",
                        "pressure_mb": 1019.0,
                        "pressure_in": 30.08,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 52,
                        "cloud": 11,
                        "feelslike_c": 18.9,
                        "feelslike_f": 66.0,
                        "windchill_c": 18.9,
                        "windchill_f": 66.0,
                        "heatindex_c": 18.9,
                        "heatindex_f": 66.0,
                        "dewpoint_c": 8.7,
                        "dewpoint_f": 47.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.6,
                        "gust_kph": 18.6,
                        "uv": 5.0,
                        "short_rad": 717.52,
                        "diff_rad": 112.58
                    },
                    {
                        "time_epoch": 1710504000,
                        "time": "2024-03-15 14:00",
                        "temp_c": 20.0,
                        "temp_f": 68.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 9.4,
                        "wind_kph": 15.1,
                        "wind_degree": 300,
                        "wind_dir": "WNW",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.06,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 53,
                        "cloud": 50,
                        "feelslike_c": 18.9,
                        "feelslike_f": 66.0,
                        "windchill_c": 18.9,
                        "windchill_f": 66.0,
                        "heatindex_c": 18.9,
                        "heatindex_f": 66.0,
                        "dewpoint_c": 8.8,
                        "dewpoint_f": 47.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.3,
                        "gust_kph": 19.9,
                        "uv": 5.0,
                        "short_rad": 734.46,
                        "diff_rad": 112.53
                    },
                    {
                        "time_epoch": 1710507600,
                        "time": "2024-03-15 15:00",
                        "temp_c": 18.6,
                        "temp_f": 65.5,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 11.2,
                        "wind_kph": 18.0,
                        "wind_degree": 319,
                        "wind_dir": "NW",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.05,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 54,
                        "cloud": 2,
                        "feelslike_c": 18.6,
                        "feelslike_f": 65.5,
                        "windchill_c": 18.6,
                        "windchill_f": 65.5,
                        "heatindex_c": 18.6,
                        "heatindex_f": 65.5,
                        "dewpoint_c": 9.0,
                        "dewpoint_f": 48.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.9,
                        "gust_kph": 20.8,
                        "uv": 5.0,
                        "short_rad": 693.62,
                        "diff_rad": 104.43
                    },
                    {
                        "time_epoch": 1710511200,
                        "time": "2024-03-15 16:00",
                        "temp_c": 18.3,
                        "temp_f": 64.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 10.5,
                        "wind_kph": 16.9,
                        "wind_degree": 328,
                        "wind_dir": "NNW",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.05,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 55,
                        "cloud": 0,
                        "feelslike_c": 18.3,
                        "feelslike_f": 64.9,
                        "windchill_c": 18.3,
                        "windchill_f": 64.9,
                        "heatindex_c": 18.3,
                        "heatindex_f": 64.9,
                        "dewpoint_c": 9.1,
                        "dewpoint_f": 48.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.7,
                        "gust_kph": 20.4,
                        "uv": 5.0,
                        "short_rad": 604.12,
                        "diff_rad": 97.74
                    },
                    {
                        "time_epoch": 1710514800,
                        "time": "2024-03-15 17:00",
                        "temp_c": 17.9,
                        "temp_f": 64.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 328,
                        "wind_dir": "NNW",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.05,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 57,
                        "cloud": 0,
                        "feelslike_c": 17.9,
                        "feelslike_f": 64.1,
                        "windchill_c": 17.9,
                        "windchill_f": 64.1,
                        "heatindex_c": 17.9,
                        "heatindex_f": 64.1,
                        "dewpoint_c": 9.2,
                        "dewpoint_f": 48.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.3,
                        "gust_kph": 19.8,
                        "uv": 5.0,
                        "short_rad": 501.92,
                        "diff_rad": 88.58
                    },
                    {
                        "time_epoch": 1710518400,
                        "time": "2024-03-15 18:00",
                        "temp_c": 17.0,
                        "temp_f": 62.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.3,
                        "wind_kph": 13.3,
                        "wind_degree": 325,
                        "wind_dir": "NW",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.06,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 59,
                        "cloud": 0,
                        "feelslike_c": 17.0,
                        "feelslike_f": 62.7,
                        "windchill_c": 17.0,
                        "windchill_f": 62.7,
                        "heatindex_c": 17.0,
                        "heatindex_f": 62.7,
                        "dewpoint_c": 9.0,
                        "dewpoint_f": 48.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.8,
                        "gust_kph": 19.0,
                        "uv": 5.0,
                        "short_rad": 396.58,
                        "diff_rad": 74.13
                    },
                    {
                        "time_epoch": 1710522000,
                        "time": "2024-03-15 19:00",
                        "temp_c": 16.6,
                        "temp_f": 61.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 7.8,
                        "wind_kph": 12.6,
                        "wind_degree": 332,
                        "wind_dir": "NNW",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.07,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 61,
                        "cloud": 0,
                        "feelslike_c": 16.6,
                        "feelslike_f": 61.9,
                        "windchill_c": 16.6,
                        "windchill_f": 61.9,
                        "heatindex_c": 16.6,
                        "heatindex_f": 61.9,
                        "dewpoint_c": 9.0,
                        "dewpoint_f": 48.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.7,
                        "gust_kph": 18.8,
                        "uv": 1.0,
                        "short_rad": 317.31,
                        "diff_rad": 59.33
                    },
                    {
                        "time_epoch": 1710525600,
                        "time": "2024-03-15 20:00",
                        "temp_c": 16.4,
                        "temp_f": 61.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.9,
                        "wind_kph": 11.2,
                        "wind_degree": 344,
                        "wind_dir": "NNW",
                        "pressure_mb": 1019.0,
                        "pressure_in": 30.08,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 61,
                        "cloud": 0,
                        "feelslike_c": 16.4,
                        "feelslike_f": 61.5,
                        "windchill_c": 16.4,
                        "windchill_f": 61.5,
                        "heatindex_c": 16.4,
                        "heatindex_f": 61.5,
                        "dewpoint_c": 8.9,
                        "dewpoint_f": 48.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.5,
                        "gust_kph": 16.8,
                        "uv": 1.0,
                        "short_rad": 264.43,
                        "diff_rad": 49.44
                    },
                    {
                        "time_epoch": 1710529200,
                        "time": "2024-03-15 21:00",
                        "temp_c": 16.2,
                        "temp_f": 61.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 5.8,
                        "wind_kph": 9.4,
                        "wind_degree": 335,
                        "wind_dir": "NNW",
                        "pressure_mb": 1019.0,
                        "pressure_in": 30.1,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 62,
                        "cloud": 0,
                        "feelslike_c": 16.2,
                        "feelslike_f": 61.1,
                        "windchill_c": 16.2,
                        "windchill_f": 61.1,
                        "heatindex_c": 16.2,
                        "heatindex_f": 61.1,
                        "dewpoint_c": 8.8,
                        "dewpoint_f": 47.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.0,
                        "gust_kph": 14.5,
                        "uv": 1.0,
                        "short_rad": 0.0,
                        "diff_rad": 0.0
                    },
                    {
                        "time_epoch": 1710532800,
                        "time": "2024-03-15 22:00",
                        "temp_c": 16.0,
                        "temp_f": 60.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.0,
                        "wind_kph": 9.7,
                        "wind_degree": 341,
                        "wind_dir": "NNW",
                        "pressure_mb": 1019.0,
                        "pressure_in": 30.1,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 63,
                        "cloud": 0,
                        "feelslike_c": 16.0,
                        "feelslike_f": 60.8,
                        "windchill_c": 16.0,
                        "windchill_f": 60.8,
                        "heatindex_c": 16.0,
                        "heatindex_f": 60.8,
                        "dewpoint_c": 8.9,
                        "dewpoint_f": 48.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.5,
                        "gust_kph": 15.2,
                        "uv": 1.0,
                        "short_rad": 0.0,
                        "diff_rad": 0.0
                    },
                    {
                        "time_epoch": 1710536400,
                        "time": "2024-03-15 23:00",
                        "temp_c": 15.8,
                        "temp_f": 60.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 7.8,
                        "wind_kph": 12.6,
                        "wind_degree": 353,
                        "wind_dir": "N",
                        "pressure_mb": 1019.0,
                        "pressure_in": 30.09,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 64,
                        "cloud": 25,
                        "feelslike_c": 15.8,
                        "feelslike_f": 60.5,
                        "windchill_c": 15.8,
                        "windchill_f": 60.5,
                        "heatindex_c": 15.8,
                        "heatindex_f": 60.5,
                        "dewpoint_c": 9.1,
                        "dewpoint_f": 48.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.3,
                        "gust_kph": 19.8,
                        "uv": 1.0,
                        "short_rad": 0.0,
                        "diff_rad": 0.0
                    }
                ]
            }
        ]
    }
}'''
category = "weather"
cursor.execute(
    "INSERT INTO endpoint (title, url, method, description, response_ex, category, api_id) VALUES (%s, %s, %s, %s, %s, %s, %s)",
    (endpoint_title,
     endpoint_url,
     method,
     description,
     response_ex,
     category,
     api_id))
endpoint_title = 'Auto'
endpoint_url = f'{THEURL}/weather/search'
method = 'GET'
description = """This endpoint will return the weather data for the next 24 hours for the location of the user."""
response_ex = """{
  body: [
    {
        "id": 681570,
        "name": "Alexandria",
        "region": "Al Iskandariyah",
        "country": "Egypt",
        "lat": 31.2,
        "lon": 29.92,
        "url": "alexandria-al-iskandariyah-egypt"
    },
    {
        "id": 2662445,
        "name": "Alexandria",
        "region": "Virginia",
        "country": "United States of America",
        "lat": 38.8,
        "lon": -77.05,
        "url": "alexandria-virginia-united-states-of-america"
    },
    {
        "id": 2015832,
        "name": "Alexandria",
        "region": "Teleorman",
        "country": "Romania",
        "lat": 43.98,
        "lon": 25.33,
        "url": "alexandria-teleorman-romania"
    },
    {
        "id": 262752,
        "name": "Alexandria",
        "region": "Rio Grande do Norte",
        "country": "Brazil",
        "lat": -6.42,
        "lon": -38.02,
        "url": "alexandria-rio-grande-do-norte-brazil"
    },
    {
        "id": 1290439,
        "name": "Alexandria",
        "region": "Saint Ann",
        "country": "Jamaica",
        "lat": 18.3,
        "lon": -77.35,
        "url": "alexandria-saint-ann-jamaica"
    }
]}"""
category = "weather"
cursor.execute(
    "INSERT INTO endpoint (title, url, method, description, response_ex, category, api_id) VALUES (%s, %s, %s, %s, %s, %s, %s)",
    (endpoint_title,
     endpoint_url,
     method,
     description,
     response_ex,
     category,
     api_id))
endpoint_title = 'History'
endpoint_url = f'{THEURL}/weather/history?q=city&dt=(Year-Month-Day)'
method = 'GET'
description = """This endpoint will return the weather data for the passed date for the location of the user."""
response_ex = '''{
body: [
    {
        "id": 681570,
        "name": "Alexandria",
        "region": "Al Iskandariyah",
        "country": "Egypt",
        "lat": 31.2,
        "lon": 29.92,
        "url": "alexandria-al-iskandariyah-egypt"
    },
    {
        "id": 2662445,
        "name": "Alexandria",
        "region": "Virginia",
        "country": "United States of America",
        "lat": 38.8,
        "lon": -77.05,
        "url": "alexandria-virginia-united-states-of-america"
    },
    {
        "id": 2015832,
        "name": "Alexandria",
        "region": "Teleorman",
        "country": "Romania",
        "lat": 43.98,
        "lon": 25.33,
        "url": "alexandria-teleorman-romania"
    },
    {
        "id": 262752,
        "name": "Alexandria",
        "region": "Rio Grande do Norte",
        "country": "Brazil",
        "lat": -6.42,
        "lon": -38.02,
        "url": "alexandria-rio-grande-do-norte-brazil"
    },
    {
        "id": 1290439,
        "name": "Alexandria",
        "region": "Saint Ann",
        "country": "Jamaica",
        "lat": 18.3,
        "lon": -77.35,
        "url": "alexandria-saint-ann-jamaica"
    }
]}'''
category = "weather"
cursor.execute(
    "INSERT INTO endpoint (title, url, method, description, response_ex, category, api_id) VALUES (%s, %s, %s, %s, %s, %s, %s)",
    (endpoint_title,
     endpoint_url,
     method,
     description,
     response_ex,
     category,
     api_id))
endpoint_title = 'future'
endpoint_url = f'{THEURL}/weather/future?q=alexandria&dt=2024-04-15'
method = 'GET'
description = "This endpoint will return the weather data for the passed date for the location of the user."
category = "weather"
response_ex = '''{
    "body": {
        "location": {
            "name": "Alexandria",
            "region": "Al Iskandariyah",
            "country": "Egypt",
            "lat": 31.2,
            "lon": 29.92,
            "tz_id": "Africa/Cairo",
            "localtime_epoch": 1710506411,
            "localtime": "2024-03-15 14:40"
        },
        "current": {
            "last_updated_epoch": 1710505800,
            "last_updated": "2024-03-15 14:30",
            "temp_c": 20.0,
            "temp_f": 68.0,
            "is_day": 1,
            "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 300,
            "wind_dir": "WNW",
            "pressure_mb": 1018.0,
            "pressure_in": 30.06,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 53,
            "cloud": 50,
            "feelslike_c": 20.0,
            "feelslike_f": 68.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "uv": 5.0,
            "gust_mph": 12.3,
            "gust_kph": 19.9
        },
        "forecast": {
            "forecastday": [
                {
                    "date": "2024-03-15",
                    "date_epoch": 1710460800,
                    "day": {
                        "maxtemp_c": 18.8,
                        "maxtemp_f": 65.8,
                        "mintemp_c": 15.2,
                        "mintemp_f": 59.3,
                        "avgtemp_c": 16.8,
                        "avgtemp_f": 62.2,
                        "maxwind_mph": 11.2,
                        "maxwind_kph": 18.0,
                        "totalprecip_mm": 0.0,
                        "totalprecip_in": 0.0,
                        "totalsnow_cm": 0.0,
                        "avgvis_km": 10.0,
                        "avgvis_miles": 6.0,
                        "avghumidity": 62,
                        "daily_will_it_rain": 0,
                        "daily_chance_of_rain": 0,
                        "daily_will_it_snow": 0,
                        "daily_chance_of_snow": 0,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "uv": 6.0
                    },
                    "astro": {
                        "sunrise": "06:10 AM",
                        "sunset": "06:09 PM",
                        "moonrise": "09:22 AM",
                        "moonset": "No moonset",
                        "moon_phase": "Waxing Crescent",
                        "moon_illumination": 28,
                        "is_moon_up": 0,
                        "is_sun_up": 0
                    },
                    "hour": [
                        {
                            "time_epoch": 1710511200,
                            "time": "2024-03-15 16:00",
                            "temp_c": 18.3,
                            "temp_f": 64.9,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 10.5,
                            "wind_kph": 16.9,
                            "wind_degree": 318,
                            "wind_dir": "NW",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.05,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 55,
                            "cloud": 2,
                            "feelslike_c": 18.3,
                            "feelslike_f": 64.9,
                            "windchill_c": 18.3,
                            "windchill_f": 64.9,
                            "heatindex_c": 18.3,
                            "heatindex_f": 64.9,
                            "dewpoint_c": 9.3,
                            "dewpoint_f": 48.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.2,
                            "gust_kph": 21.2,
                            "uv": 5.0,
                            "short_rad": 655.8,
                            "diff_rad": 98.4
                        },
                        {
                            "time_epoch": 1710514800,
                            "time": "2024-03-15 17:00",
                            "temp_c": 17.9,
                            "temp_f": 64.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 9.6,
                            "wind_kph": 15.5,
                            "wind_degree": 328,
                            "wind_dir": "NNW",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.05,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 57,
                            "cloud": 0,
                            "feelslike_c": 17.9,
                            "feelslike_f": 64.1,
                            "windchill_c": 17.9,
                            "windchill_f": 64.1,
                            "heatindex_c": 17.9,
                            "heatindex_f": 64.1,
                            "dewpoint_c": 9.2,
                            "dewpoint_f": 48.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 12.3,
                            "gust_kph": 19.8,
                            "uv": 5.0,
                            "short_rad": 501.92,
                            "diff_rad": 88.58
                        },
                        {
                            "time_epoch": 1710518400,
                            "time": "2024-03-15 18:00",
                            "temp_c": 17.0,
                            "temp_f": 62.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 8.3,
                            "wind_kph": 13.3,
                            "wind_degree": 325,
                            "wind_dir": "NW",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.06,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 59,
                            "cloud": 0,
                            "feelslike_c": 17.0,
                            "feelslike_f": 62.7,
                            "windchill_c": 17.0,
                            "windchill_f": 62.7,
                            "heatindex_c": 17.0,
                            "heatindex_f": 62.7,
                            "dewpoint_c": 9.0,
                            "dewpoint_f": 48.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.8,
                            "gust_kph": 19.0,
                            "uv": 5.0,
                            "short_rad": 396.58,
                            "diff_rad": 74.13
                        },
                        {
                            "time_epoch": 1710522000,
                            "time": "2024-03-15 19:00",
                            "temp_c": 16.6,
                            "temp_f": 61.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 7.8,
                            "wind_kph": 12.6,
                            "wind_degree": 332,
                            "wind_dir": "NNW",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.07,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 61,
                            "cloud": 0,
                            "feelslike_c": 16.6,
                            "feelslike_f": 61.9,
                            "windchill_c": 16.6,
                            "windchill_f": 61.9,
                            "heatindex_c": 16.6,
                            "heatindex_f": 61.9,
                            "dewpoint_c": 9.0,
                            "dewpoint_f": 48.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.7,
                            "gust_kph": 18.8,
                            "uv": 1.0,
                            "short_rad": 317.31,
                            "diff_rad": 59.33
                        },
                        {
                            "time_epoch": 1710525600,
                            "time": "2024-03-15 20:00",
                            "temp_c": 16.4,
                            "temp_f": 61.5,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.9,
                            "wind_kph": 11.2,
                            "wind_degree": 344,
                            "wind_dir": "NNW",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.08,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 61,
                            "cloud": 0,
                            "feelslike_c": 16.4,
                            "feelslike_f": 61.5,
                            "windchill_c": 16.4,
                            "windchill_f": 61.5,
                            "heatindex_c": 16.4,
                            "heatindex_f": 61.5,
                            "dewpoint_c": 8.9,
                            "dewpoint_f": 48.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 10.5,
                            "gust_kph": 16.8,
                            "uv": 1.0,
                            "short_rad": 264.43,
                            "diff_rad": 49.44
                        },
                        {
                            "time_epoch": 1710529200,
                            "time": "2024-03-15 21:00",
                            "temp_c": 16.2,
                            "temp_f": 61.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 5.8,
                            "wind_kph": 9.4,
                            "wind_degree": 335,
                            "wind_dir": "NNW",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.1,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 62,
                            "cloud": 0,
                            "feelslike_c": 16.2,
                            "feelslike_f": 61.1,
                            "windchill_c": 16.2,
                            "windchill_f": 61.1,
                            "heatindex_c": 16.2,
                            "heatindex_f": 61.1,
                            "dewpoint_c": 8.8,
                            "dewpoint_f": 47.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.0,
                            "gust_kph": 14.5,
                            "uv": 1.0,
                            "short_rad": 0.0,
                            "diff_rad": 0.0
                        },
                        {
                            "time_epoch": 1710532800,
                            "time": "2024-03-15 22:00",
                            "temp_c": 16.0,
                            "temp_f": 60.8,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.0,
                            "wind_kph": 9.7,
                            "wind_degree": 341,
                            "wind_dir": "NNW",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.1,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 63,
                            "cloud": 0,
                            "feelslike_c": 16.0,
                            "feelslike_f": 60.8,
                            "windchill_c": 16.0,
                            "windchill_f": 60.8,
                            "heatindex_c": 16.0,
                            "heatindex_f": 60.8,
                            "dewpoint_c": 8.9,
                            "dewpoint_f": 48.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.5,
                            "gust_kph": 15.2,
                            "uv": 1.0,
                            "short_rad": 0.0,
                            "diff_rad": 0.0
                        },
                        {
                            "time_epoch": 1710536400,
                            "time": "2024-03-15 23:00",
                            "temp_c": 15.8,
                            "temp_f": 60.5,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly Cloudy ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 7.8,
                            "wind_kph": 12.6,
                            "wind_degree": 353,
                            "wind_dir": "N",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.09,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 64,
                            "cloud": 25,
                            "feelslike_c": 15.8,
                            "feelslike_f": 60.5,
                            "windchill_c": 15.8,
                            "windchill_f": 60.5,
                            "heatindex_c": 15.8,
                            "heatindex_f": 60.5,
                            "dewpoint_c": 9.1,
                            "dewpoint_f": 48.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 12.3,
                            "gust_kph": 19.8,
                            "uv": 1.0,
                            "short_rad": 0.0,
                            "diff_rad": 0.0
                        }
                    ]
                }
            ]
        }
    }
}'''
cursor.execute(
    "INSERT INTO endpoint (title, url, method, description, response_ex, category, api_id) VALUES (%s, %s, %s, %s, %s, %s, %s)",
    (endpoint_title,
     endpoint_url,
     method,
     description,
     response_ex,
     category,
     api_id))
title = "exchange rate"
description = "Get the latest foreign exchange reference rates in JSON format."
category = "finance"
image_cover = Image.open("image1.png")
with open("image1.png", "rb") as image_file:
    image = f'data:image/{image_cover.format};base64,{base64.b64encode(image_file.read()).decode()}'
# Insert data into the table
insert_query = "INSERT INTO API (title, description, category, image_cover) VALUES (%s, %s, %s, %s)"
cursor.execute(insert_query, (title, description, category, image))
endpoint_title = "exchange rate"
description = "get the least exchange rate for a currency"
endpoint_url = f"{THEURL}/currency?base=EGP"
response_ex = """{
  "base": "EGP",
  "date": "2024-03-15",
  "rates": {
    "AED": 0.076812,
    "AFN": 1.497018,
    "ALL": 1.993177,
    "AMD": 8.474607,
    "ANG": 0.037919,
    "AOA": 17.415712,
    "ARS": 17.784198,
    "AUD": 0.031842,
    "AWG": 0.03765,
    "AZN": 0.035643,
    "BAM": 0.03761,
    "BBD": 0.042484,
    "BDT": 2.309124,
    "BGN": 0.037553,
    "BHD": 0.007884,
    "BIF": 60.166437,
    "BMD": 0.020916,
    "BND": 0.028018,
    "BOB": 0.1454,
    "BRL": 0.104365,
    "BSD": 0.021041,
    "BTC": 0,
    "BTN": 1.742096,
    "BWP": 0.285294,
    "BYN": 0.068847,
    "BYR": 409.962081,
    "BZD": 0.042412,
    "CAD": 0.028299,
    "CDF": 57.896688,
    "CHF": 0.018451,
    "CLF": 0.000711,
    "CLP": 19.617947,
    "CNY": 0.150517,
    "COP": 81.429764,
    "CRC": 10.745655,
    "CUC": 0.020916,
    "CUP": 0.554285,
    "CVE": 2.120421,
    "CZK": 0.48331,
    "DJF": 3.746749,
    "DKK": 0.143183,
    "DOP": 1.243404,
    "DZD": 2.811162,
    "EGP": 1,
    "ERN": 0.313746,
    "ETB": 1.194704,
    "EUR": 0.019201,
    "FJD": 0.046848,
    "FKP": 0.016408,
    "GBP": 0.016399,
    "GEL": 0.055432,
    "GGP": 0.016408,
    "GHS": 0.271435,
    "GIP": 0.016408,
    "GMD": 1.421276,
    "GNF": 180.836095,
    "GTQ": 0.164281,
    "GYD": 4.401992,
    "HKD": 0.163609,
    "HNL": 0.518094,
    "HRK": 0.143955,
    "HTG": 2.789486,
    "HUF": 7.549881,
    "IDR": 326.758604,
    "ILS": 0.076485,
    "IMP": 0.016408,
    "INR": 1.732781,
    "IQD": 27.562182,
    "IRR": 879.222244,
    "ISK": 2.85489,
    "JEP": 0.016408,
    "JMD": 3.257733,
    "JOD": 0.014828,
    "JPY": 3.109175,
    "KES": 2.813168,
    "KGS": 1.872223,
    "KHR": 85.072973,
    "KMF": 9.458478,
    "KPW": 18.824264,
    "KRW": 27.827118,
    "KWD": 0.006429,
    "KYD": 0.017534,
    "KZT": 9.423793,
    "LAK": 437.676353,
    "LBP": 1872.020724,
    "LKR": 6.429125,
    "LRD": 4.029556,
    "LSL": 0.392593,
    "LTL": 0.061761,
    "LVL": 0.012652,
    "LYD": 0.100504,
    "MAD": 0.210944,
    "MDL": 0.370829,
    "MGA": 94.687911,
    "MKD": 1.181107,
    "MMK": 44.184487,
    "MNT": 71.039773,
    "MOP": 0.169523,
    "MRU": 0.834665,
    "MUR": 0.961752,
    "MVR": 0.322056,
    "MWK": 35.202353,
    "MXN": 0.348691,
    "MYR": 0.098401,
    "MZN": 1.328434,
    "NAD": 0.392383,
    "NGN": 33.262361,
    "NIO": 0.769753,
    "NOK": 0.221275,
    "NPR": 2.787377,
    "NZD": 0.034291,
    "OMR": 0.008052,
    "PAB": 0.021041,
    "PEN": 0.077348,
    "PGK": 0.08036,
    "PHP": 1.161531,
    "PKR": 5.83568,
    "PLN": 0.08241,
    "PYG": 153.704402,
    "QAR": 0.076146,
    "RON": 0.095442,
    "RSD": 2.250587,
    "RUB": 1.916887,
    "RWF": 26.940365,
    "SAR": 0.078444,
    "SBD": 0.175629,
    "SCR": 0.280845,
    "SDG": 8.774274,
    "SEK": 0.21607,
    "SGD": 0.027962,
    "SHP": 0.026632,
    "SLE": 0.475774,
    "SLL": 475.774199,
    "SOS": 11.952609,
    "SRD": 0.737649,
    "STD": 432.927927,
    "SVC": 0.184107,
    "SYP": 271.948694,
    "SZL": 0.391424,
    "THB": 0.748526,
    "TJS": 0.230391,
    "TMT": 0.073417,
    "TND": 0.064768,
    "TOP": 0.04944,
    "TRY": 0.673853,
    "TTD": 0.142859,
    "TWD": 0.661342,
    "TZS": 53.472918,
    "UAH": 0.813958,
    "UGX": 81.747708,
    "USD": 0.020916,
    "UYU": 0.816392,
    "UZS": 264.410801,
    "VEF": 75755.11268,
    "VES": 0.757838,
    "VND": 517.054217,
    "VUV": 2.499761,
    "WST": 0.057288,
    "XAF": 12.613972,
    "XAG": 0.00083,
    "XAU": 1e-05,
    "XCD": 0.056528,
    "XDR": 0.015753,
    "XOF": 12.613972,
    "XPF": 2.29131,
    "YER": 5.23642,
    "ZAR": 0.39014,
    "ZMK": 188.272934,
    "ZMW": 0.523911,
    "ZWL": 6.735083
  },
  "success": true,
  "timestamp": 1710534426778
}
"""
cursor.execute('SELECT id FROM API WHERE title = "exchange rate"')
id = cursor.fetchone()[0]
_ = cursor.fetchall()
cursor.execute(
    "INSERT INTO endpoint (title, url, method, description, response_ex, category, api_id) VALUES (%s, %s, %s, %s, %s, %s, %s)",
    (endpoint_title,
     endpoint_url,
     method,
     description,
     response_ex,
     category,
     id))
connection.commit()
cursor.close()
connection.close()
